# Generated by Django 2.0.2 on 2018-03-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulating_supply', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('name', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('symbol', models.CharField(default='', max_length=6)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulating_supply', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('datetime', models.IntegerField(default=0)),
                ('historical_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('name', models.CharField(default='', max_length=30)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=30)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
