# Generated by Django 2.0.2 on 2018-04-24 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('circulating_supply', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('name', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('rank', models.IntegerField(default=0)),
                ('symbol', models.CharField(default='', max_length=6)),
                ('price_change_day', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('price_change_hour', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('price_change_week', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulating_supply', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 19, 30, 27, 782288))),
                ('historical_price', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('name', models.CharField(default='', max_length=30)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 19, 30, 27, 783000))),
                ('name', models.CharField(default='', max_length=30)),
                ('predicted_price', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='historical',
            unique_together={('name', 'datetime')},
        ),
    ]
