# Generated by Django 2.0.2 on 2018-03-22 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 16, 53, 15, 657290)),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 16, 53, 15, 659186)),
        ),
    ]
