# Generated by Django 2.0.2 on 2018-04-26 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='strategy',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='historical',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 26, 16, 45, 59, 164404)),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 26, 16, 45, 59, 164854)),
        ),
    ]
