# Generated by Django 2.0.2 on 2018-03-22 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0002_auto_20180322_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 18, 12, 35, 162076)),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 18, 12, 35, 163065)),
        ),
    ]
