# Generated by Django 2.0.2 on 2018-04-18 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0003_auto_20180322_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 18, 14, 3, 50, 989761)),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 18, 14, 3, 50, 990737)),
        ),
    ]
