# Generated by Django 2.0.2 on 2018-04-18 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0005_auto_20180418_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 18, 15, 26, 6, 116381)),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 18, 15, 26, 6, 117510)),
        ),
    ]
