# Generated by Django 2.0.2 on 2018-04-19 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0007_auto_20180418_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 18, 21, 38, 40, 212714)),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 18, 21, 38, 40, 213798)),
        ),
    ]
